from rotor import Rotor, Reflector, InputRotor
from interface import Interface

ROTOR_1 = Rotor(1, 17, {"A": "E",
                        "B": "K",
                        "C": "M",
                        "D": "F",
                        "E": "L",
                        "F": "G",
                        "G": "D",
                        "H": "Q",
                        "I": "V",
                        "J": "Z",
                        "K": "N",
                        "L": "T",
                        "M": "O",
                        "N": "W",
                        "O": "Y",
                        "P": "H",
                        "Q": "X",
                        "R": "U",
                        "S": "S",
                        "T": "P",
                        "U": "A",
                        "V": "I",
                        "W": "B",
                        "X": "R",
                        "Y": "C",
                        "Z": "J",
                        })

ROTOR_2 = Rotor(2, 5, {"A": "A",
                       "B": "J",
                       "C": "D",
                       "D": "K",
                       "E": "S",
                       "F": "I",
                       "G": "R",
                       "H": "U",
                       "I": "X",
                       "J": "B",
                       "K": "L",
                       "L": "H",
                       "M": "W",
                       "N": "T",
                       "O": "M",
                       "P": "C",
                       "Q": "Q",
                       "R": "G",
                       "S": "Z",
                       "T": "N",
                       "U": "P",
                       "V": "Y",
                       "W": "F",
                       "X": "V",
                       "Y": "O",
                       "Z": "E",
                       })

ROTOR_3 = Rotor(3, 22, {"A": "B",
                        "B": "D",
                        "C": "F",
                        "D": "H",
                        "E": "J",
                        "F": "L",
                        "G": "C",
                        "H": "P",
                        "I": "R",
                        "J": "T",
                        "K": "X",
                        "L": "V",
                        "M": "Z",
                        "N": "N",
                        "O": "Y",
                        "P": "E",
                        "Q": "I",
                        "R": "W",
                        "S": "G",
                        "T": "A",
                        "U": "K",
                        "V": "M",
                        "W": "U",
                        "X": "S",
                        "Y": "Q",
                        "Z": "O",
                        })

ROTOR_4 = Rotor(4, 2, {"A": "E",
                       "B": "S",
                       "C": "O",
                       "D": "V",
                       "E": "P",
                       "F": "Z",
                       "G": "J",
                       "H": "A",
                       "I": "Y",
                       "J": "Q",
                       "K": "U",
                       "L": "I",
                       "M": "R",
                       "N": "H",
                       "O": "X",
                       "P": "L",
                       "Q": "N",
                       "R": "F",
                       "S": "T",
                       "T": "G",
                       "U": "K",
                       "V": "D",
                       "W": "C",
                       "X": "M",
                       "Y": "W",
                       "Z": "B",
                       })

ROTOR_5 = Rotor(5, 0, {"A": "V",
                       "B": "Z",
                       "C": "B",
                       "D": "R",
                       "E": "G",
                       "F": "I",
                       "G": "T",
                       "H": "Y",
                       "I": "U",
                       "J": "P",
                       "K": "S",
                       "L": "D",
                       "M": "N",
                       "N": "H",
                       "O": "L",
                       "P": "X",
                       "Q": "A",
                       "R": "W",
                       "S": "M",
                       "T": "J",
                       "U": "Q",
                       "V": "O",
                       "W": "F",
                       "X": "E",
                       "Y": "C",
                       "Z": "K",
                       })

REFLECTOR_B = Reflector("B", {"A": "Y",
                              "B": "R",
                              "C": "U",
                              "D": "H",
                              "E": "Q",
                              "F": "S",
                              "G": "L",
                              "P": "I",
                              "V": "W",
                              "X": "J",
                              "K": "N",
                              "T": "Z",
                              "M": "O",
                              })

REFLECTOR_C = Reflector("C", {"A": "F",
                              "B": "V",
                              "C": "P",
                              "D": "J",
                              "E": "I",
                              "G": "O",
                              "H": "Y",
                              "K": "R",
                              "L": "Z",
                              "M": "X",
                              "N": "W",
                              "T": "Q",
                              "S": "U",
                              })
